//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int ID_Movie { get; set; }
        public int Producer_ID { get; set; }
        public int Film_ID { get; set; }
        public string Age_Rating { get; set; }
        public int Price { get; set; }
        public string Payment_of_Pushkin_card { get; set; }
    
        public virtual Films Films { private get; set; }
        public virtual Producers Producers { private get; set; }
    }
}
