//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewsi
    {
        public string Название_фильма { get; set; }
        public string Описание_фильма { get; set; }
        public string Фамилия_режиссера { get; set; }
        public string Имя_режиссера { get; set; }
        public string Отчество_режиссера { get; set; }
        public string Возрастные_ограничения { get; set; }
        public int Цена_за_билет { get; set; }
        public string Оплата_Пушкинсокй_картой { get; set; }
    }
}
